### ISSUE TITLE
push all git tags

### ISSUE THREAD

**Issue by edehde** [ezrapagel/knife-vsphere#102]
Could you please push the tags of all released <http://rubygems.org/gems/knife-vsphere/versions> so that e.g. the <https://github.com/ezrapagel/knife-vsphere/releases.atom> feed can be used to better track updates.

Thanks,
Eike

--
@edehde

**Comment by swalberg** [comment]
Hi, I'm not sure the tags are available anymore unless Ezra has them in his local repo. As an alternative, https://rubygems.org/gems/knife-vsphere/versions.atom has the information you're looking for.
