### ISSUE TITLE
vm config does not work for DynamicData 

### ISSUE THREAD

**Issue by tcicone** [ezrapagel/knife-vsphere#113]
I can set some parameters using config, but not others. 

Setting cpuHotAddEnabled works.

# knife vsphere vm query acicone-virt config.cpuHotAddEnabled --folder LAB --vsuser root
Enter your password:
true
# knife vsphere vm config acicone-virt cpuHotAddEnabled false --folder LAB --vsuser root
Enter your password:
#
# knife vsphere vm query acicone-virt config.cpuHotAddEnabled --folder LAB --vsuser root
Enter your password:
false

But, setting thinProvisioned does not.

# knife vsphere vm query acicone-virt config.hardware.device[11].backing.thinProvisioned --folder LAB --vsuser root
Enter your password:
true

# knife vsphere vm config acicone-virt thinProvisioned false --folder LAB --vsuser root
Enter your password:
ERROR: RuntimeError: unexpected property name thinProvisioned

# knife vsphere vm config acicone-virt config.hardware.device[11].backing.thinProvisioned false --folder LAB --vsuser root
Enter your password:
ERROR: RuntimeError: unexpected property name config.hardware.device[11].backing.thinProvisioned

Do I need different syntax?

Thanks for your help.

**Comment by swalberg** [comment]
Hi, is this still a problem? I'm sorry that it's sat unaddressed for this long.

**Comment by tcicone** [comment]
Nope, I updated the scripts to do the thin and thick provisioning on a move and clone.

Thanks.

**Comment by swalberg** [comment]
Thanks! Closing.
