### ISSUE TITLE
Can't specify trusted SSL certificate

### ISSUE THREAD

**Issue by hufman** [ezrapagel/knife-vsphere#129]
I can't find how to specify a trusted cert to use when communicating with my vcenter server. I tried doing `knife ssl fetch` and the cert shows up in my trusted_certs directory, but `knife vsphere` ignores it.
I'd prefer to give a trusted cert instead of opening the ssl connection wide open.

**Comment by swalberg** [comment]
Are you talking about the VSphere API interaction or the communication between the chef client and the server? I think to talk to the VSphere API you need to get the vsphere key in your local certificate store. `trusted_certs` is only used for the Chef API.

**Comment by swalberg** [comment]
Hi, closing this as we haven't heard back in a little while. If you're still interested in discussing this, please re-open and let me know. Thanks.
