### ISSUE TITLE
After knife vm clone network will always be detached

### ISSUE THREAD

**Issue by TD-4242** [ezrapagel/knife-vsphere#138]
After knife vm clone network will always be detached.  I can go in and attach it quickly from the vsphere UI.  and if done prior to timeout the node will boot strap.

What might cause my network to always show up as detached?

**Comment by troyready** [comment]
Have you tried applying a customization specification to the cloned VM? I believe the nic will be attached at the end of the process.

**Comment by TD-4242** [comment]
I've done that at least twice while troubleshooting.  I may check on my vm tools install and make sure it's fully up to date.  Though I'm not sure it would be vmware tools causing this.

**Comment by DennisBP** [comment]
Do you change your network settings with options like --cvlan, --cips or --cdomain?

If so this is a normal behavior. After the first boot VMware tries to configure the network settings without a network connection. If everything is done VMware is going to reboot the VM and connect the network card.

**Comment by TD-4242** [comment]
I'm guessing this has something to do with my template.  I have a new template that I'm using that doesn't have this problem and I can bootstrap a node as I should be able to.  the other template will not connect the network for me at all.

**Comment by DennisBP** [comment]
Have both templates the same operating system?

I had this problem with CentOS 7 and I had to change the /etc/redhat-release file to "Red Hat Enterprise Linux Server release 7.0 (Maipo)".

**Comment by MattMencel** [comment]
@TD-4242 This is a problem we've bumped into too....so I found some code to get around it when it happens.  This is an old copy of our bootstrap code.  Look for the "Resetting NIC" section.

https://gist.github.com/MattMencel/5302820

After the VM is cloned, but before we power it on, we just disconnect the NIC from the VM then reconnect it.  Kind of hacky but it works for us.

**Comment by TD-4242** [comment]
This seems to be working on a new template.  Not sure why the old one didn't work.

Going to close this issue.

**Comment by bodinewilson** [comment]
I... don't suppose there are any updates on this?  Looks like it' still happening for me, and I'd love to be able to change adapter status on a vmxnet3 adapter

**Comment by swalberg** [comment]
Hi, the only time I've ever run into this has been when we had a vSphere 5.x problem where port numbers would get reused, and ever since upgrading we haven't seen it.

When we create the VM we don't have an option to start it up connected or not. It's usually up to vSphere and the template. If you turn your template into a VM and start it up, is the NIC connected?

**Comment by bodinewilson** [comment]
It is now, but it wasn't previously when I sent my inquiry.

I was planning on using that functionality in order to re-connect it after
the clone as a workaround.

thx!
