### ISSUE TITLE
Plugin is not working for DHCP

### ISSUE THREAD

**Issue by ManishMehra** [ezrapagel/knife-vsphere#143]
Hi

I tried to use this plugin in following fashion. It worked
>>knife vsphere vm clone VM1 --template Ubuntu12 --cips 10.5.5.180/24 --cgw 10.5.5.250 --cdnsips 8.8.8.8 --chostname VM1 --cdomain imslab.com --ccpu 1 --cram 1 --start STARTVM

But when I tried it for DHCP, it's not working. What changes should I do to make it work for DHCP?
Please suggest solution.

**Comment by swalberg** [comment]
Hi,

That was fixed in #141. I don't think a new gem has been released so you'll need to install from master:

```
gem uninstall knife-vsphere
git clone git@github.com:ezrapagel/knife-vsphere.git
cd knife-vsphere
rake build
gem install pkg/knife-vsphere-1.0.0.gem.
```

Then you can pass `--cips dhcp` and drop the `--cgw`

**Comment by swalberg** [comment]
Manish, did this work for you?

**Comment by ManishMehra** [comment]
Hi Swalberg

Yes, We finished testing that use case yesterday. That is working fine now. Thanks.

Regards
Manish Mehra
