### ISSUE TITLE
Modify existing VM in terms of RAM and HDD.

### ISSUE THREAD

**Issue by ManishMehra** [ezrapagel/knife-vsphere#145]
Hi

We have already provisioned VM using knife-vsphere. Is it possible to modify VM using the same? Please guide.

Thanks and Regards
Manish Mehra

**Comment by swalberg** [comment]
`knife vsphere vm config` might be able to get you there for the memory. I'm not sure it's robust enough to do a disk. The memory property is `memoryMB`.

`vm.ReconfigVM_Task(spec: { memoryMB: options["size"] }).wait_for_completion` is what I have in some of the code we use around here for management outside of this plugin.

**Comment by ManishMehra** [comment]
Hi Swalberg

Thanks. It works for the RAM. Could you please send me the property name for HDD. Let me try doing it for HDD as well. 

Regards

**Comment by swalberg** [comment]
Hi Manish, I don't know how to do it for HDD as it's not a single property. Have a look at the [config spec](http://pubs.vmware.com/vi3/sdk/ReferenceGuide/vim.vm.ConfigSpec.html) documentation from VMWare to give you an idea of what the properties look like.

**Comment by ManishMehra** [comment]
Hi Swalberg

Thanks. For now we are dropping the modification of HDD.

**Comment by radiumx3** [comment]
any clue to modify cpu spec ?

**Comment by swalberg** [comment]
Hi @radiumx3 , try `numCPUs`. Have a look at https://www.vmware.com/support/developer/vc-sdk/visdk25pubs/ReferenceGuide/vim.vm.ConfigSpec.html for other things you can try.
