### ISSUE TITLE
knife vpshere vm clone using cplugin option failing

### ISSUE THREAD

**Issue by kamalim** [ezrapagel/knife-vsphere#148]
I am using the following command:
`knife vsphere vm clone test1 --template windows_server_2008_r2 --cplugin ./knife_windows_cplugin.rb --cplugin-data ./data.rb`

But it fails with error FATAL: Please provide Windows Guest Customization
So I created a customization spec (though I would want to avoid it) and the used the below command
`knife vsphere vm clone test1 --template windows_server_2008_r2 --cplugin "./knife_windows_cplugin.rb" --cplugin-data "data.rb" --cspec "windows_spec.xml"`

but it failed with below error 

```
/Users/kamalim/.rvm/gems/ruby-2.0.0-p598/gems/rbvmomi-1.8.2/lib/rbvmomi/connection.rb:61:in `parse_response': NotFound: The object or item referred to could not be found. (RbVmomi::Fault)
	from /Users/kamalim/.rvm/gems/ruby-2.0.0-p598/gems/rbvmomi-1.8.2/lib/rbvmomi/connection.rb:90:in `call'
	from /Users/kamalim/.rvm/gems/ruby-2.0.0-p598/gems/rbvmomi-1.8.2/lib/rbvmomi/basic_types.rb:205:in `_call'
	from /Users/kamalim/.rvm/gems/ruby-2.0.0-p598/gems/rbvmomi-1.8.2/lib/rbvmomi/basic_types.rb:74:in `block (2 levels) in init'
	from /Users/kamalim/.rvm/gems/ruby-2.0.0-p598/gems/knife-vsphere-1.0.1/lib/chef/knife/vsphere_vm_clone.rb:499:in `find_customization'
	from /Users/kamalim/.rvm/gems/ruby-2.0.0-p598/gems/knife-vsphere-1.0.1/lib/chef/knife/vsphere_vm_clone.rb:402:in `generate_clone_spec'
	from /Users/kamalim/.rvm/gems/ruby-2.0.0-p598/gems/knife-vsphere-1.0.1/lib/chef/knife/vsphere_vm_clone.rb:265:in `run'
	from /Users/kamalim/.rvm/gems/ruby-2.0.0-p598/gems/chef-12.2.1/lib/chef/knife.rb:419:in `block in run_with_pretty_exceptions'
	from /Users/kamalim/.rvm/gems/ruby-2.0.0-p598/gems/chef-12.2.1/lib/chef/local_mode.rb:38:in `with_server_connectivity'
	from /Users/kamalim/.rvm/gems/ruby-2.0.0-p598/gems/chef-12.2.1/lib/chef/knife.rb:418:in `run_with_pretty_exceptions'
	from /Users/kamalim/.rvm/gems/ruby-2.0.0-p598/gems/chef-12.2.1/lib/chef/knife.rb:214:in `run'
	from /Users/kamalim/.rvm/gems/ruby-2.0.0-p598/gems/chef-12.2.1/lib/chef/application/knife.rb:138:in `run'
	from /Users/kamalim/.rvm/gems/ruby-2.0.0-p598/gems/chef-12.2.1/bin/knife:25:in `<top (required)>'
	from /Users/kamalim/.rvm/gems/ruby-2.0.0-p598/bin/knife:23:in `load'
	from /Users/kamalim/.rvm/gems/ruby-2.0.0-p598/bin/knife:23:in `<main>'
	from /Users/kamalim/.rvm/gems/ruby-2.0.0-p598/bin/ruby_executable_hooks:15:in `eval'
	from /Users/kamalim/.rvm/gems/ruby-2.0.0-p598/bin/ruby_executable_hooks:15:in `<main>'
```

So I have how can I use my customized plugin without Windows Customization spec or is there any other option.I am using the custom plugin as specified in the readme.

**Comment by kamalim** [comment]
here is my knife_windows_cplugin.rb
require 'rbvmomi'

class KnifeVspherePlugin
  attr_accessor :data

  def customize_clone_spec(src_config, clone_spec)

    if File.exists? data
      customization_data = JSON.parse(IO.read(data))
    else
      abort "Customization plugin data file #{data} not accessible"
    end

    cust_guiUnattended = RbVmomi::VIM.CustomizationGuiUnattended(
      :autoLogon => false,
      :autoLogonCount => 1,
      :password => nil,
      :timeZone => customization_data['timeZone']
    )
    cust_identification = RbVmomi::VIM.CustomizationIdentification(
      :domainAdmin => nil,
      :domainAdminPassword => nil,
      :joinDomain => nil
    )
    cust_name = RbVmomi::VIM.CustomizationFixedName(
      :name => customization_data['host_name']
    )
    cust_user_data = RbVmomi::VIM.CustomizationUserData(
      :computerName => cust_name,
      :fullName => customization_data['fullName'],
      :orgName => customization_data['orgName'],
      :productId => customization_data['windows_key']
    )
    cust_sysprep = RbVmomi::VIM.CustomizationSysprep(
      :guiUnattended => cust_guiUnattended,
      :identification => cust_identification,
      :userData => cust_user_data
    )
    dhcp_ip = RbVmomi::VIM.CustomizationDhcpIpGenerator
    cust_ip = RbVmomi::VIM.CustomizationIPSettings(
      :ip => dhcp_ip
    )
    cust_adapter_mapping = RbVmomi::VIM.CustomizationAdapterMapping(
      :adapter => cust_ip
    )
    cust_adapter_mapping_list = [cust_adapter_mapping]
    global_ip = RbVmomi::VIM.CustomizationGlobalIPSettings
    customization_spec = RbVmomi::VIM.CustomizationSpec(
      :identity => cust_sysprep,
      :globalIPSettings => global_ip,
      :nicSettingMap => cust_adapter_mapping_list
    )
    clone_spec.customization = customization_spec
    puts "New clone_spec object :\n #{YAML::dump(clone_spec)}"
    clone_spec
  end

  def reconfig_vm (target_vm)
    puts "In reconfig_vm method.  No actions implemented.."
  end
end

**Comment by swalberg** [comment]
Hi, I'm not sure offhand as I haven't used any Windows or external class customization specs.

I've added a bit of formatting to your comments in hopes someone might be able to figure it out.

**Comment by swalberg** [comment]
Just on a hunch, how did you come up with `--cspec "windows_spec.xml"` ? That cspec should be defined on your vsphere server with the name of `windows_spec.xml`, it's not a reference to a local file.

**Comment by swalberg** [comment]
Going to close this as there's been no response. Please re-open it if the problem persists. Thanks.
