### ISSUE TITLE
--cdnsips leaves my /etc/resolv.conf empty (mostly)

### ISSUE THREAD

**Issue by TD-4242** [ezrapagel/knife-vsphere#152]
This is deploying an Ubuntu 14.04 host.  I can't seem to get --cdnsips and --cdnssuffix to add items to the VM at startup so it fails trying to install chef.  I'm using:

--cips 'x.x.x.11'
--cgw 'x.x.x.1'
--cdnsips 'x.x.x.10'
--cdnssuffix 'example.com'

my /etc/network/interfaces gets populated with the ip and gw.  but /etc/resolv.conf looks like:

<pre>
vagrant@testhost:~$ cat /etc/resolv.conf
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
vagrant@testhost:~$
</pre>

and the dns-nameserver items are not added to /etc/network/interfaces

<pre>
vagrant@testhost:~$ cat /etc/network/interfaces
iface lo inet loopback
auto lo

auto eth0
iface eth0 inet static
address x.x.x.11
netmask 255.255.255.0
up route add default gw x.x.x.1
vagrant@testhost:~$
</pre>

Am I doing something wrong?

**Comment by swalberg** [comment]
Hi,

The first thing to check is that the template's VMWare tools are up to date.

**Comment by TD-4242** [comment]
Fixed it with a vcenter patch.

**Comment by swalberg** [comment]
Thanks for the update. Do you have some details about which patch you applied and the software versions you were on? Someone may come by later with the same query, so this will be helpful for the future.

Thanks.

**Comment by TD-4242** [comment]
Our guests were Ubuntu 14.04 and were not supported on our version of Vcenter based on the VMWare support matrix.  We patched Vcenter to the latest and it all works now.  The patch level we are using at the time of this fix is 'Version 5.5.0 Build 2414847' Unfortunately I don't have the previous version number we were on when it was broken, but from memory it was around build 18XXXXX.

**Comment by swalberg** [comment]
Thanks, Bill. I'm sure there's enough there that someone with the same problem will trip over this and now know what to do.
