### ISSUE TITLE
knife vsphere template list returns empty list

### ISSUE THREAD

**Issue by devilldog** [ezrapagel/knife-vsphere#154]
I have tried this from both windows and linux but it returns an empty list, all other commands work with the list option.. using knife-vsphere 1.0.1

**Comment by devilldog** [comment]
except vm list returns 1 host ...

**Comment by skymob** [comment]
@devilldog are your templates contained in a folder? If I don't pass `--folder` to the command, I get an empty list as well, but this returns the expected results:
```
$ bundle exec knife vsphere template list --folder templates
Template Name: win7pro64-tmpl
Template Name: centos63-08072012
...
```

**Comment by devilldog** [comment]
yes i figured that out thanks !
