### ISSUE TITLE
clone returns VM/Template not found

### ISSUE THREAD

**Issue by devilldog** [ezrapagel/knife-vsphere#155]
should this not work given I have a working knife.rb ?

knife vsphere vm clone test --template 'Templates/Linux/RHEL BASE 6.6'

**Comment by swalberg** [comment]
What kind of error are you getting? I've never tried loading my templates from a folder, but I think you'd want something like

`knife vsphere vm clone test --folder 'Templates/Linux' --template 'RHEL BASE 6.6'`

instead

**Comment by devilldog** [comment]
sorry "VM/Template" not found, I am using the path to the templates from vm list

**Comment by devilldog** [comment]
i That was it,was not evident from the docs... thanks ! I have another issue but i will close this one
