### ISSUE TITLE
This may be a bug in the 'vsphere vm clone' knife command or plugin

### ISSUE THREAD

**Issue by devilldog** [ezrapagel/knife-vsphere#156]
when running:
```
knife vsphere vm clone --verbose xxx  --folder 'Templates/Gold/BaseServer' --template 'Server-2012-R2-(STD)'  --cspec auto-svr-2012-xx  --cips xx.xx.xx.xx/24 --cgw  x.x.x.x. --chostname xxxx --cdomain xx.xx.net --dest-folder 'xx/Insfrastructure' --datastore 'xtremeio_vol_5' --ccpu 4 --cram 8 --start true --bootstrap true --thin-provision --vsdc 'xx' --run-list 'xx-tomcat:default'
```

INFO: Using configuration from /home/xx/chef-repo/.chef/knife.rb
DEBUG: value for config item bootstrap: true
DEBUG: value for config item distro:
DEBUG: value for config item vsphere_host: xx.xx.com
DEBUG: value for config item vshere_path:
DEBUG: value for config item vsphere_port: 443
DEBUG: value for config item vsphere_nossl:
DEBUG: value for config item vsphere_user: xx\xx
DEBUG: value for config item vsphere_pass: base64:xx==
DEBUG: value for config item vsphere_insecure: true
DEBUG: value for config item proxy_host:
DEBUG: value for config item proxy_port:
DEBUG: value for config item vsphere_dc: xx
DEBUG: value for config item folder: Templates/Gold/BaseServer
DEBUG: value for config item vsphere_dc: xx
DEBUG: value for config item linked_clone:
DEBUG: value for config item resource_pool:
DEBUG: value for config item vsphere_dc: xx
DEBUG: value for config item linked_clone:
DEBUG: value for config item datastore: xtremeio_vol_5
DEBUG: value for config item datastorecluster:
DEBUG: value for config item datastore: xtremeio_vol_5
DEBUG: value for config item datastore: xtremeio_vol_5
DEBUG: value for config item vsphere_dc: xx
DEBUG: value for config item datastorecluster:
DEBUG: value for config item thin_provision: true
DEBUG: value for config item resource_pool:
DEBUG: value for config item vsphere_dc: xx
ERROR: knife encountered an unexpected error
This may be a bug in the 'vsphere vm clone' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NoMethodError: undefined method `split' for nil:NilClass

Just a q, I see there are blank attributes above are they all needed  ?

**Comment by swalberg** [comment]
The blank attributes should be ok. This debugging info is coming from `knife` itself.

Do you get a stack trace with line numbers at all? I'm not sure offhand where the `nil` is coming from.

**Comment by devilldog** [comment]
doh ! not sure how I missed coping that...
[{WIFEXITED(s) && WEXITSTATUS(s) == 100}], 0, NULL) = 10950
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
--- SIGCHLD (Child exited) @ 0 (0) ---
wait4(-1, 0x7fff71eed29c, WNOHANG, NULL) = -1 ECHILD (No child processes)
rt_sigreturn(0xffffffffffffffff)        = 0
rt_sigaction(SIGINT, {SIG_DFL, [], SA_RESTORER, 0x30256326a0}, {0x43d050, [], SA_RESTORER, 0x30256326a0}, 8) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
read(255, "", 462)                      = 0
exit_group(100)                         = ?

**Comment by devilldog** [comment]
No, just the output above, thought the empty attributes  may be causing split to return nil.

**Comment by swalberg** [comment]
What does your `knife.rb` look like? I took a glance through any instance of `split` that you might be hitting and they're all guarded by an `if` clause. But I do see a typo in a couple of places, so I'm wondering if that `split` is happening in Rbvmobi or maybe knife.

**Comment by devilldog** [comment]
i added resourcepool to the command and the error went away, we dont use resourcepools but i used the name of the cluster and it worked....
