### ISSUE TITLE
Boot strapping windows 

### ISSUE THREAD

**Issue by devilldog** [ezrapagel/knife-vsphere#158]
so after looking at the code it appears that i cannot bootstrap windows with winrm is that correct ?seems like it may not be much work to add it ...

**Comment by swalberg** [comment]
Honestly I don't know -- I don't do any Windows work. There are a couple of pull requests that seem to address this but they included many other code cleanups and they didn't get the reviews they deserved.

I'm happy to work with you as much as I can to get the minimum viable implementation of Windows support in here. This project has no tests, alas, so big changes are scary changes.

**Comment by devilldog** [comment]
so I was able to set the ssh port to the winrm port and and once the server was up and the port was up knife completed successfully. I just ran a second knife command to boot strap the node. I will look at the code further see if I can get it working, and test against both windows and linux.

**Comment by mheidenr** [comment]
@devilldog you can bootstrap windows with winrm. Make sure to set up winrm on the target machine like this [Autounattend.xml](https://github.com/joefitzgerald/packer-windows/blob/master/answer_files/2012_r2/Autounattend.xml#L112) does. Then you can do ```knife bootstrap windows winrm %VM_NAME% --environment %ENVIRONMENT% -P %WINDOWS_ADMIN_PASSWORD% -N %VM_NAME%```.

**Comment by tim95030** [comment]
I have a pull request I recently merged master into my branch that we have been using to do full windows clones with customization. The only issue at this point is I cannot find a way other then to sleep a lengthy period to determine when the sysprep has finished. There appears to be a message in the event log, but I am not very familiar with Vsphere api and couldn't find an easy way to get this information from the API. Anyways with that small issue aside the branch does work to clone windows. You can see it here: https://github.com/ezrapagel/knife-vsphere/pull/137

**Comment by mheidenr** [comment]
Hi @tim95030 please see, if PR #164 fits your needs

**Comment by swalberg** [comment]
Hey @devilldog can you grab the latest version of this gem and see if it lets you get a full bootstrap with winrm?

**Comment by troyready** [comment]
I just ran my first test and it's working great for me -- thanks everyone for coming together on this one.

**Comment by swalberg** [comment]
Glad to hear it. @devilldog I'm going to close this, but if you have any problems getting a Windows machine going, please don't hesitate to reopen this issue or create a new one.
