### ISSUE TITLE
vsphere vm clone gives an error

### ISSUE THREAD

**Issue by dmitriy-panasiuk** [ezrapagel/knife-vsphere#174]
Hi,

i am getting this error when trying to clone a vm from a template
`knife vsphere vm clone cloned_vm -f Templates --template clean2012r2 --dest-folder test -VV`

INFO: Using configuration from C:/chef-repo/.chef/knife.rb
DEBUG: value for config item chef_node_name:
DEBUG: value for config item vsphere_host: xxxxx.global.sdl.corp
DEBUG: value for config item vsphere_path: /sdk
DEBUG: value for config item vsphere_port: 443
DEBUG: value for config item vsphere_nossl:
DEBUG: value for config item vsphere_user: xxxxxx
DEBUG: value for config item vsphere_pass: xxxxxxx
DEBUG: value for config item vsphere_insecure: true
DEBUG: value for config item proxy_host:
DEBUG: value for config item proxy_port:
DEBUG: value for config item vsphere_dc: xxxx
DEBUG: value for config item folder: Templates
DEBUG: value for config item vsphere_dc: xxxx
DEBUG: value for config item linked_clone:
DEBUG: value for config item resource_pool:
DEBUG: value for config item vsphere_dc: xxxx
DEBUG: value for config item datastore:
DEBUG: value for config item datastorecluster:
DEBUG: value for config item customization_vlan:
DEBUG: value for config item linked_clone:
DEBUG: value for config item datastore:
DEBUG: value for config item datastore:
DEBUG: value for config item datastorecluster:
DEBUG: value for config item thin_provision:
DEBUG: value for config item mark_as_template:
DEBUG: value for config item annotation:
DEBUG: value for config item customization_cpucount:
DEBUG: value for config item customization_memory:
DEBUG: value for config item customization_vlan:
DEBUG: value for config item customization_spec:
DEBUG: value for config item customization_dns_ips:
DEBUG: value for config item customization_dns_suffixes:
DEBUG: value for config item disable_customization:
DEBUG: value for config item customization_domain:
DEBUG: Identified os as windows.
C:/Users/Administrator/.chefdk/gem/ruby/2.1.0/gems/knife-vsphere-1.2.2/lib/chef/knife/vsphere_vm_clone.rb:547:in `genera
te_clone_spec': undefined method `identification' for nil:NilClass (NoMethodError)
        from C:/Users/Administrator/.chefdk/gem/ruby/2.1.0/gems/knife-vsphere-1.2.2/lib/chef/knife/vsphere_vm_clone.rb:3
10:in `run'
        from C:/opscode/chefdk/embedded/apps/chef/lib/chef/knife.rb:422:in `block in run_with_pretty_exceptions'
        from C:/opscode/chefdk/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
        from C:/opscode/chefdk/embedded/apps/chef/lib/chef/knife.rb:421:in `run_with_pretty_exceptions'
        from C:/opscode/chefdk/embedded/apps/chef/lib/chef/knife.rb:214:in `run'
        from C:/opscode/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:142:in `run'
        from C:/opscode/chefdk/embedded/apps/chef/bin/knife:25:in `<top (required)>'
        from C:/opscode/chefdk/bin/knife:63:in `load'
        from C:/opscode/chefdk/bin/knife:63:in `<main>'

**Comment by dsopscak** [comment]
I am getting the same error doing a clone operation, both from a template and source vm. The guest is windows 2012r2. Running knife from a win7 workstation. I'm able to list items and also turn existing VM's on and off, but the clone fails as above.

**Comment by swalberg** [comment]
So at first glance it looks like we're not setting an [identity](http://pubs.vmware.com/vi30/sdk/ReferenceGuide/vim.vm.customization.Specification.html) over in https://github.com/ezrapagel/knife-vsphere/blob/master/lib/chef/knife/vsphere_vm_clone.rb#L517. 

Can you try it with a customization spec on the server? `--cspec`

**Comment by swalberg** [comment]
cc/ @tim95030 and @mheidenr

**Comment by dsopscak** [comment]
Using a customization spec did get me past the error. But that's not a feature I've set up before and had been getting acceptable defaults (cloning with the  vsphere .net api) apparently based on the source of the clone. I can see the value in using it but will need to figure out how to get it configured  right and it's not necessarily something we'll want to use all the time.

**Comment by swalberg** [comment]
I agree this is not a solution. Just wanted to verify my hypothesis and get you a temporary workaround. We'll be looking at this.

**Comment by mheidenr** [comment]
@dmitriy-panasiuk @dsopscak please try PR #175 
@swalberg please wait for their confirmation

**Comment by dmitriy-panasiuk** [comment]
The fix worked for me. Specifying --cspec option also does the job, so it is a valid workaround.
Thx guys!

**Comment by dsopscak** [comment]
The fix got me past the original problem. I now see an error like

ERROR: RbVmomi::Fault: NicSettingMismatch: fault.NicSettingMismatch.summary

which may well be expected: the template I'm cloning from has two NIC's and I saw the same error when using a cspec until I added a second NIC to it. In a case like this, is using a cspec the only option?

Sorry for an off-topic question, but not sure where else to ask: Is it possible to get the --run-list option to work when running knife in local mode?

**Comment by swalberg** [comment]
@dsopscak you can pass multiple IP that are comma separated: `--cips 192.168.0.99/24,192.168.1.99/24 ` and the resulting customization spec will have entries for both NICs.

I'm sorry, but I don't follow your second question.

**Comment by swalberg** [comment]
I've merged #175 and released as version 1.2.3. `gem install knife-vsphere` or grab it from git.

**Comment by swalberg** [comment]
Thanks for the quick fix @mheidenr! And also thanks to @dmitriy-panasiuk and @dsopscak for reporting the bug and testing the fix.

**Comment by dsopscak** [comment]
@swalberg Thanks for all the help on this.

I tried using `--cips '*dhcp*,*dhcp*'` which I gathered from the README is how you configure an interface for DHCP, but got 

ERROR: NetAddr::ValidationError: Could not auto-detect IP version for '\*dhcp\*'

My second question relates to getting a runlist applied to the newly cloned VM. I was hoping there may be a way to use cookbooks in the local filesystem by runing knife in local `-z` mode. The VM is cloned from a template that already has chef client installed. I'm pretty new to chef and I'm afraid that is naive on my part, that a full-fledged chef server may be required for that.

**Comment by swalberg** [comment]
Hi, the asterisks are not literals, you should be able to to `--cips dhcp,dhcp`.

This plugin uses the Knife bootstrap code to get Chef on the box. There's nothing stopping you from using this plugin to clone the VM, then writing your own scripts to copy the cookbooks over and then ssh in to run chef in solo mode. See https://docs.chef.io/chef_solo.html for that latter part. That said, you may be able to automate it better with a bootstrap template (https://docs.chef.io/knife_bootstrap.html)
