### ISSUE TITLE
Clone fails -- NicSettingMismatch

### ISSUE THREAD

**Issue by theborch** [ezrapagel/knife-vsphere#18]
Ubuntu 12.04 x64

`knife vsphere vm clone newvmname --template U1204x64 -f Templates -VV`

Results in this:

Cloning template U1204x64 to new VM newvmname
/home/user/.rvm/gems/ruby-1.9.2-p318/gems/rbvmomi-1.5.1/lib/rbvmomi/vim/Task.rb:11:in 'wait_for_completion': **NicSettingMismatch: fault.NicSettingMismatch.summary (RbVmomi::Fault)**
	from /home/user/.rvm/gems/ruby-1.9.2-p318/gems/knife-vsphere-0.1.8/lib/chef/knife/vsphere_vm_clone.rb:195:in 'run'
	from /home/user/.rvm/gems/ruby-1.9.2-p318/gems/chef-0.10.8/lib/chef/knife.rb:391:in 'run_with_pretty_exceptions'
	from /home/user/.rvm/gems/ruby-1.9.2-p318/gems/chef-0.10.8/lib/chef/knife.rb:166:in 'run'
	from /home/user/.rvm/gems/ruby-1.9.2-p318/gems/chef-0.10.8/lib/chef/application/knife.rb:128:in 'run'
	from /home/user/.rvm/gems/ruby-1.9.2-p318/gems/chef-0.10.8/bin/knife:25:in '<top (required)>'
	from /home/user/.rvm/gems/ruby-1.9.2-p318/bin/knife:19:in 'load'
	from /home/user/.rvm/gems/ruby-1.9.2-p318/bin/knife:19:in '<main>'

**Comment by swalberg** [comment]
Looks like this was solved. Closing, but please open a new issue referencing this one if there are more problems.
