### ISSUE TITLE
knife vsphere vm vmdk add - unknown vm : undefined method `datastore'

### ISSUE THREAD

**Issue by gitfirenz** [ezrapagel/knife-vsphere#182]
Hello,

When you "vmdk add" and the vm is unknown (mistyped by exemple), the test ".nil" does not work.

So you have an "datastore" error :(

/root/.chefdk/gem/ruby/2.1.0/gems/knife-vsphere-1.2.2/lib/chef/knife/vsphere_vm_vmdk_add.rb:57:in `run': undefined method `datastore' for false:FalseClass (NoMethodError)
 
The error must be in these lines (i'm not a ruby coder) : 

    vm = get_vm(vmname)
    if vm.nil?
      puts "Could not find #{vmname}"
      return
    end

    target_lun = get_config(:target_lun) unless get_config(:target_lun).nil?
    vmdk_size_kb = size.to_i * 1024 * 1024

    if target_lun.nil?
      vmdk_datastore = choose_datastore(vm.datastore, size)
      exit -1 if vmdk_datastore.nil?
    else

**Comment by swalberg** [comment]
Yes, our error checking leaves something to be desired. Can you give me a quick example and output just so I'm sure what you're referring to, please?

Thanks.

**Comment by gitfirenz** [comment]
I send you this back to my work monday.
