### ISSUE TITLE
knife vsphere vm clone - --bootstrap FALSE does not work

### ISSUE THREAD

**Issue by gitfirenz** [ezrapagel/knife-vsphere#183]
Hello again,

When i clone a vm from a template, the chef-bootstrap process is started, even if i use the option --boostrap FALSE.

I tried in lowercase too (--bootstrap false), and no option since it seems the default.

Checking the code, it seems there is no test at all :)

(seek at "    Chef::Log.debug("Connect Host for Bootstrap: #{connect_host}")").

**Comment by swalberg** [comment]
Hey! Thanks for the bug report. I'm gone until the 8th but will look at this then.

I'm wondering if [this](https://github.com/ezrapagel/knife-vsphere/blob/master/lib/chef/knife/vsphere_vm_clone.rb#L129) should be `boolean: true`. Any chance you can try it out in your local copy?

And yes, a thousand pardons for no tests. I've been playing with some cucumber stuff (https://github.com/swalberg/knife-vsphere/tree/cucumber) but progress is slow as I need to mock the whole rbvmomi library.

**Comment by gitfirenz** [comment]
I'll try monday.

**Comment by tim95030** [comment]
As far as I can tell from my phone the code looks correct. You should not define bootstrap on the command line if you don't want it.   

--bootstrap

Means true there is no input to that.

Can you show me the full command you are running?

**Comment by swalberg** [comment]
My guess is that the option is set as "Boolean: false" so it's getting
treated as a string. And an empty string is not falsely.

On Saturday, August 1, 2015, tim95030 <notifications@github.com> wrote:

> As far as I can tell from my phone the code looks correct. You should not
> define bootstrap on the command line if you don't want it.
>
> --bootstrap
>
> Means true there is no input to that.
>
> Can you show me the full command you are running?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ezrapagel/knife-vsphere/issues/183#issuecomment-126961200>
> .
>


-- 
Sean Walberg <sean@ertw.com>    http://ertw.com/

**Comment by gitfirenz** [comment]
You are right.

After a test, if i does not specify"--bootstrap", it does NOT bootstrap.
If i specify boostrap (as false, true, FALSE), it bootstrap.

I was doing a "knife vsphere vm clone toto --bootstrap FALSE".

So i think a documentation update is enough.

**Comment by tim95030** [comment]
Ok. Good. I was pretty sure that was what was happening. The boolean switches are a little less obvious than most.

**Comment by swalberg** [comment]
See #187 for some doc fixes. Thanks @gitfirenz for bringing this one up; I never would have noticed otherwise.
