### ISSUE TITLE
Executing command on linux guest

### ISSUE THREAD

**Issue by maishsk** [ezrapagel/knife-vsphere#28]
While running 
knife vsphere vm execute test2 -f LAB touch /tmp/1.tst --exec-user root --exec-passwd xxxxx --exec-dir /usr/bin - I receive an error

ERROR: RbVmomi::Fault: FileNotFound: File <unspecified filename> was not found

running with -VV

root@Chef:~# knife vsphere vm execute test2 -f LAB touch /tmp/1.tst --exec-user root --exec-passwd xxxxx --exec-dir /usr/bin -VV
DEBUG: Using configuration from /root/.chef/knife.rb
DEBUG: value for config item vsphere_host: vc.maishsk.local
DEBUG: value for config item vshere_path: 
DEBUG: value for config item vsphere_port: 443
DEBUG: value for config item vsphere_nossl: 
DEBUG: value for config item vsphere_user: maish
DEBUG: value for config item vsphere_pass: xxxxx
DEBUG: value for config item vsphere_insecure: true
DEBUG: value for config item vsphere_dc: LAB
DEBUG: value for config item folder: LAB
DEBUG: value for config item vsphere_dc: LAB
DEBUG: value for config item exec_dir: /usr/bin
/usr/local/rvm/gems/ruby-1.9.3-p125/gems/rbvmomi-1.5.1/lib/rbvmomi/connection.rb:61:in `parse_response': FileNotFound: File <unspecified filename> was not found (RbVmomi::Fault)
	from /usr/local/rvm/gems/ruby-1.9.3-p125/gems/rbvmomi-1.5.1/lib/rbvmomi/connection.rb:90:in `call'
	from /usr/local/rvm/gems/ruby-1.9.3-p125/gems/rbvmomi-1.5.1/lib/rbvmomi/basic_types.rb:203:in `_call'
	from /usr/local/rvm/gems/ruby-1.9.3-p125/gems/rbvmomi-1.5.1/lib/rbvmomi/basic_types.rb:74:in `block (2 levels) in init'
	from /usr/local/rvm/gems/ruby-1.9.3-p125/gems/knife-vsphere-0.3.0/lib/chef/knife/vsphere_vm_execute.rb:65:in `run'
	from /usr/local/rvm/gems/ruby-1.9.3-p125/gems/chef-10.16.2/lib/chef/knife.rb:408:in `run_with_pretty_exceptions'
	from /usr/local/rvm/gems/ruby-1.9.3-p125/gems/chef-10.16.2/lib/chef/knife.rb:168:in `run'
	from /usr/local/rvm/gems/ruby-1.9.3-p125/gems/chef-10.16.2/lib/chef/application/knife.rb:123:in `run'
	from /usr/local/rvm/gems/ruby-1.9.3-p125/gems/chef-10.16.2/bin/knife:25:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-1.9.3-p125/bin/knife:19:in `load'
	from /usr/local/rvm/gems/ruby-1.9.3-p125/bin/knife:19:in `<main>'
	from /usr/local/rvm/gems/ruby-1.9.3-p125/bin/ruby_noexec_wrapper:14:in `eval'
	from /usr/local/rvm/gems/ruby-1.9.3-p125/bin/ruby_noexec_wrapper:14:in `<main>'

**Comment by swalberg** [comment]
Hi, is this still happening? Happy to help debug if so.

**Comment by swalberg** [comment]
I was able to reproduce this locally. The argument parsing is a bit hairy.

If you have a command with an option, such as "/bin/cat /etc/hosts", then do not quote it. You want to run

`knife vsphere vm execute VMNAME /bin/cat /etc/hosts --blah`

What's happening is that the command is getting broken up into arguments and the command itself. If you quote it, it's trying to run the whole thing:

```
GuestProgramSpec(
  arguments: "",
  programPath: "/bin/ls /home",
  workingDirectory: "/root"
)
```

if you separate it out, it works better:

```
GuestProgramSpec(
  arguments: "/home",
  programPath: "/bin/ls",
  workingDirectory: "/root"
)
```

**Comment by swalberg** [comment]
Hi, I'm closing this issue. If the problem persists, please reopen it and we can resume the conversation.
