### ISSUE TITLE
Assign mac address to multple nics

### ISSUE THREAD

**Issue by rtsai123** [ezrapagel/knife-vsphere#32]
Hi,

I just started using knife-vsphere gem and I say that this is a life saver. So thanks for working on it!   Since I am new to to this, I wanted to know how to assign mac addresses to clone vm with multiple nics?  Is that even possible with knife vsphere clone command?

Thanks,
Robert

**Comment by swalberg** [comment]
Hi, this issue has sat here for a long time and I'm sorry that no one has helped you with it. I'm closing old issues, but if you're still having a problem please re-open or start a new thread.
