### ISSUE TITLE
Clone WIndows VM (winrm) with Bootstrap Option ?

### ISSUE THREAD

**Issue by amosin** [ezrapagel/knife-vsphere#33]
It seems like the --bootstrap option will not work when cloning a Windows VM that has winrm setup.

Waiting for sshd...DEBUG: value for config item ssh_port: 22
.DEBUG: value for config item ssh_port: 22
.DEBUG: value for config item ssh_port: 22
.DEBUG: value for config item ssh_port: 22

**Comment by swade1987** [comment]
i am getting the same problem however mine just hangs on "Waiting for sshd..." any ideas?

**Comment by swalberg** [comment]
Hey folks, can you have a look at the latest version of this plugin? winrm support was recently added.

Closing this issue. If you end up with any problems do let us know by opening a new issue.
