### ISSUE TITLE
vmdk add command failure

### ISSUE THREAD

**Issue by vishalkatikineni** [ezrapagel/knife-vsphere#40]
I get the below error when I try to add a virtual disk to my VM.

vkatikineni@vishal-vm1:~$ knife vsphere vm vishal-vm1.tnt17-zone1.aus1 vmdk add 10 -f tenant17/DBA --vmdk-type thick -VV
DEBUG: value for config item vsphere_host:
DEBUG: value for config item vshere_path:
DEBUG: value for config item vsphere_port: 443
DEBUG: value for config item vsphere_nossl:
DEBUG: value for config item vsphere_user: tenant17
DEBUG: value for config item vsphere_pass:
DEBUG: value for config item vsphere_insecure: true
DEBUG: value for config item folder: tenant17/DBA
DEBUG: value for config item vsphere_dc: MP1
DEBUG: value for config item vmdk_type: thick

Creating VMDK
Capacity: 10 GB
Disk: [ea29-p2k1-fs01-tnt17] vishal-vm1.tnt17-zone1.aus1/vishal-vm1.tnt17-zone1.aus1_1.vmdk
Datastore: Datastore("datastore-2360")
DEBUG: value for config item vsphere_dc: MP1
Attaching VMDK to vishal-vm1.tnt17-zone1.aus1
DEBUG: value for config item noop:
/usr/local/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/rbvmomi-1.5.1/lib/rbvmomi/vim/Task.rb:11:in wait_for_completion': InvalidType: The request refers to an unexpected or unknown type. (RbVmomi::Fault)
from /usr/local/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/knife-vsphere-0.5.0/lib/chef/knife/vsphere_vm_vmdk_add.rb:71:inrun'
from /usr/local/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/knife.rb:460:in run_with_pretty_exceptions'
from /usr/local/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/knife.rb:173:inrun'
from /usr/local/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/application/knife.rb:123:in run'
from /usr/local/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/chef-11.4.4/bin/knife:25:in'
from /usr/local/rbenv/versions/1.9.2-p290/bin/knife:23:in load'
from /usr/local/rbenv/versions/1.9.2-p290/bin/knife:23:in'

**Comment by swalberg** [comment]
Hi, I'm sorry this issue sat for so long with no help. I'm going to close this, but if you still need help feel free to re-open it or create a new issue and we'll jump right on it.
