### ISSUE TITLE
vm clone fails with connection reset by peer

### ISSUE THREAD

**Issue by vishalkatikineni** [ezrapagel/knife-vsphere#41]
Cloning template template-ubuntu-12.04-25gig-tnt17 to new VM vishal-vm6.tnt17-zone1.aus1
ERROR: Errno::ECONNRESET: Connection reset by peer

**Comment by swalberg** [comment]
Hi, this is a fairly old request and I'm sorry no one has come to help you yet. Is the problem still happening?
Thanks.

**Comment by swalberg** [comment]
Hi, I'm going to close this to try and clean up our backlog of inactive issues. If you are still having this problem, please make sure you're running the latest version of the gem (`gem install knife-vsphere`) first, and then open a new issue so that it goes to the top of the list. Thanks.
