### ISSUE TITLE
knife[:vsphere_dc] should be able to take an array of dcs

### ISSUE THREAD

**Issue by aaronjwhiteside** [ezrapagel/knife-vsphere#47]
knife[:vsphere_dc] = [ 'dc1', 'dc2' ]

**Comment by swalberg** [comment]
Interesting thought, though how would we know which is the right one to use? Could you instead do something like

```
knife[:vsphere_dc] = ENV['vsphere_dc'] || 'dc1'
```

And then

```
knife vsphere # uses dc1
vsphere_dc=dc2 knive vsphere # uses dc2
```

**Comment by swalberg** [comment]
Hi, closing this as it's fairly old. If you are still interested in discussing this, please re-open. Thanks.
