### ISSUE TITLE
chef-related switches ignored

### ISSUE THREAD

**Issue by hinder90** [ezrapagel/knife-vsphere#52]
Hi, I am cloning a VM and bootstrapping with chef and attempting to specify that chef 11.4.4 is used but it is apparently being ignored. I also noticed earlier that setting  "--bootstrap FALSE" doesn't do anything either- it will still bootstrap. Is --disable-customization causing them to be ignored?

knife vsphere vm clone bork --template precise64-basebox-dhcp -VV --disable-customization --node-name bork --start STARTVM --ssh-user ubuntu --ssh-password nermal --bootstrap TRUE --bootstrap-version 11.4.4 --run-list recipe[getting-started]

**Comment by swalberg** [comment]
Hi, is this issue still happening? I'm cleaning up old issues and want to see if we need to do any more work here.

Thanks.

**Comment by hinder90** [comment]
Hard to say, I’ve moved on from this project and can’t verify. Sorry.


On May 20, 2015 at 12:58:36 PM, Sean Walberg (notifications@github.com) wrote:

Hi, is this issue still happening? I'm cleaning up old issues and want to see if we need to do any more work here.

Thanks.

**Comment by swalberg** [comment]
No problem. Thanks for getting back to me. I'll close this, and if anyone else reports it they can open up a new issue and we can look at it with fresh eyes.
