### ISSUE TITLE
Logging of VSphere events

### ISSUE THREAD

**Issue by hinder90** [ezrapagel/knife-vsphere#60]
As part of the logging options, perhaps when using debug, it would be very helpful if all all of the VSphere event logs pertaining to the knife action could be reported for a specified event log level. At this time, it would appear the only VSphere event log information that ever gets returned is in the case of a fatal error.

**Comment by swalberg** [comment]
Hi, I'm sorry this has taken so long to get a reply. I was thinking of this the other day as I was helping some people troubleshoot some problems. Will be putting together a PR for at least the `vm clone` case shortly.
