### ISSUE TITLE
Debugging knife-vsphere

### ISSUE THREAD

**Issue by NicCOConnor** [ezrapagel/knife-vsphere#61]
I realize this is probably the wrong forum for this question however I cannot find a better place to ask. I've asked in the IRC channel, read numerous documents and I still cannot find an answer. I'm looking to implement windows bootstrapping with the knife-vsphere plugin. I am shamelessly trying to integrate the code in the knife-vcloud source. I think I've gotten it to a point where I can start to test But this is where I'm having trouble. I can't seem to debug knife-vsphere properly and I can't find any documentation on how to debug a knife plugin. can anybody point me in the right direction. I'm currently using Eclipse IDE but I'm open to suggestions. 

My current issue is when I run the script it dies before getting to the run method. I can only assume that this is implemented in the knife.rb file or a subset of that however I can't figure it out. Can anyone here point me in the right direction?

Do I have to have the chef/knife source in order to debug or is installing the gem enough? Can anyone provide any examples of Debug Configurations needed in Eclipse? Can I only Debug with UNIT testing and if so does anyone have a resource for getting this setup in Eclipse. I Don't have much experience with unit testing. 

Thanks in advance to anyone that can help me out.

Nic

**Comment by swalberg** [comment]
Hi Nic, sorry no one has responded to you. Are you still looking into this? Or did you have any success on your own?

**Comment by swalberg** [comment]
Closing. You may want to check out the recent additions that handle Windows bootstrapping. Feel free to resume the conversation by re-opening this issue.
