### ISSUE TITLE
use of the "--distro" flag is required in verion 0.9.5 bootstrap cmd

### ISSUE THREAD

**Issue by honeybagder** [ezrapagel/knife-vsphere#64]
FYI in testing v0.9.5 I am finding that to provision and bootstrap a node requires use of the `--distro` flag in the command. If this flag and a corresponding value is not set, I am seeing the following error:
`Can not find bootstrap definition for`
`ERROR: Errno::ENOENT: No such file or directory`  
With verbose output enabled I am seeing that knife is looking for a bootstrap template.

This may be intended behavior as a default value for `:distro` was removed from `lib/chef/knife/vsphere_vm_clone.rb`
Perhaps this should be added to the README or otherwise noted.

**Comment by swalberg** [comment]
Hi, I think this has been fixed since 0.9.5. If you're still having problems after upgrading, please let me know.
