### ISSUE TITLE
Can't clone template across resource pools

### ISSUE THREAD

**Issue by nixwiz** [ezrapagel/knife-vsphere#66]
Within our datacenter we have two resources pools (DRS/HA clusters), DevQA and Production.  All of our templates reside within the DevQA resource pool.  I am not able to clone from the template with the destination pool being Production.

This works:

knife vsphere vm clone toddtest -f Templates --template RHLinux664 --vshost c3pivcenter1.corp.premierinc.com -u tcampbel  --vsinsecure --resource-pool DevQA --dest-folder "DEVQA Linux Servers" --verbose --cips 10.32.32.248/24 --cgw 10.32.32.1 --chostname toddtest --ccpu 1 --cram 2 --cspec RHEL --cvlan "10.32.32 VM Net" --start

But when atttempting to use the Production resource pool (and Folder as well):

knife vsphere vm clone toddtest -f Templates --template RHLinux664 --vshost c3pivcenter1.corp.premierinc.com -u tcampbel  --vsinsecure --resource-pool Production --dest-folder "Production Linux Servers" --verbose --cips 10.32.32.248/24 --cgw 10.32.32.1 --chostname toddtest --ccpu 1 --cram 2 --cspec RHEL --cvlan "10.32.32 VM Net" --start

It generates the error:

ERROR: RbVmomi::Fault: CannotAccessVmComponent: A component of the virtual machine is not accessible on the host.

This is our pool list:

knife vsphere pool list --vshost c3pivcenter1.corp.premierinc.com -u tcampbel  --vsinsecure                                                                                                                                                                    
Enter your password: 
Folder: 
ClusterComputeResource: DevQA
VirtualApp: DevQA/Resources/ProSphere
Unknown type VirtualApp, not enumerating
ClusterComputeResource: Production
ClusterComputeResource: StackTest
ClusterComputeResource: VDI

**Comment by swalberg** [comment]
Hi, I'm just seeing this issue and I'm very sorry you haven't received a response.

Is this still happening?

**Comment by swalberg** [comment]
Hi, I'm going to close this to try and clean up our backlog of inactive issues. If you are still having this problem, please make sure you're running the latest version of the gem (`gem install knife-vsphere`) first, and then open a new issue so that it goes to the top of the list. Thanks.
