### ISSUE TITLE
Issue with odd error:  RbVmomi::Fault: NotFound:

### ISSUE THREAD

**Issue by brujack** [ezrapagel/knife-vsphere#68]
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/rbvmomi-1.5.1/lib/rbvmomi/connection.rb:61:in `parse_response': NotFound: The object or item referred to could not be found. (RbVmomi::Fault)
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/rbvmomi-1.5.1/lib/rbvmomi/connection.rb:90:in `call'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/rbvmomi-1.5.1/lib/rbvmomi/basic_types.rb:203:in `_call'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/rbvmomi-1.5.1/lib/rbvmomi/basic_types.rb:74:in `block (2 levels) in init'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/knife-vsphere-0.9.5/lib/chef/knife/vsphere_vm_clone.rb:405:in `find_customization'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/knife-vsphere-0.9.5/lib/chef/knife/vsphere_vm_clone.rb:309:in `generate_clone_spec'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/knife-vsphere-0.9.5/lib/chef/knife/vsphere_vm_clone.rb:223:in `run'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/knife.rb:466:in `run_with_pretty_exceptions'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/knife.rb:173:in `run'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/lib/chef/application/knife.rb:123:in `run'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.0/bin/knife:25:in `<top (required)>'
	from /usr/bin/knife:23:in `load'
	from /usr/bin/knife:23:in `<main>'

**Comment by swalberg** [comment]
Hi, I'm sorry that this has sat unaddressed for so long. Is the problem still happening?

**Comment by swalberg** [comment]
Closing. If you're still having this problem, please re-open the issue and we'll continue the conversation.

**Comment by venkateshseerapu** [comment]
Yes, I'm getting this when try spin off new VM

below is the exception message:
ERROR: RbVmomi::Fault: NotFound: The object or item referred to could not be found.

**Comment by kaizoku0506** [comment]
I am hitting this issue as well.  When I attempt to build a new VM using a text ESX host with datastore01 build on local storage, there is no issue at all.  However, when I move this into one of the production environments, I get:

CannotAccessVmConfig: Unable to access the virtual machine configuration: Unable to access file [datastore-odd-01] RHEL6Template/RHEL6Template.vmtx

**Comment by swalberg** [comment]
Hi, I missed the updates here. We resolved the problem in #254 -- use `--resource_pool` to specify a cluster that has access to the template and/or datastore.
