### ISSUE TITLE
vm clone windows template?

### ISSUE THREAD

**Issue by lamont** [ezrapagel/knife-vsphere#74]
Apologies if this more of a general question than an issue, but is it currently possible to clone a windows vm with any amount of spec customization? Or does anybody have an example of a custom spec plugin that does that? I keep getting the error "A specified parameter was not correct: spec.identity" and when I dumped the identity spec I see:

identity: CustomizationLinuxPrep(...

so i assume that's the root of my error. 

What I'm looking to do is clone a windows VM, change the hostname and ip, regenerate the sid, change the admin password. 

My (sanitized) command line is:
knife vsphere vm clone lamont-test --template W2008R2_STD_x64_template --chostname lamont-test --cdomain foo.xxxxxxx.com --cips yyy.zzz.67.106/24 --cvlan hav-guest-dev-4 --folder templates --resource-pool "poolfolder/realpool" --ccpu 2 --cram 2 --cdnsips "1.2.3.4,1.2.3.5" --cdnssuffix foo.xxxxxxxx.com

I'm running against vsphere 5.0.0, knife vsphere plugin 0.9.5.

Looking at the vmware api docs, it seems like I could swap the CustomizationLinuxPrep for CustomizationSysprepText and use that to write out the sysprep.inf file. Does that seem like a reasonable task to accomplish via a spec plugin?

Thank you.

**Comment by swalberg** [comment]
Closing as this seems to be solved. If not, please re-open or create a new issue.
