### ISSUE TITLE
-cspec does not work with windows

### ISSUE THREAD

**Issue by itzdilip** [ezrapagel/knife-vsphere#82]
I have created a custom spec in vcenter and passed the name, it said it is not supported for windows, I wanted to know fix or alternative or work around for doing the same

**Comment by swalberg** [comment]
Hi, is this happening with the latest version of the gem? If so please update this issue with some command output and some pointers on how to reproduce this. Thanks.

**Comment by swalberg** [comment]
Hi, I'm going to close this to try and clean up our backlog of inactive issues. If you are still having this problem, please make sure you're running the latest version of the gem (`gem install knife-vsphere`) first, and then open a new issue so that it goes to the top of the list. Thanks.

**Comment by itzdilip** [comment]
hi,

it was quite some time before, these days I have not used, if i encounter I will post it across!

Thanks
