### ISSUE TITLE
knife vsphere vm execute run in undefined method 'processManager'

### ISSUE THREAD

**Issue by oviis** [ezrapagel/knife-vsphere#83]
knife vsphere vm execute CloneTest -f folder "/usr/bin/uptime" -VV --exec-user root --exec-passwd xxx --exec-dir /root -u user

run in following error
-----
DEBUG: value for config item exec_dir: /root
/var/lib/gems/1.9.1/gems/knife-vsphere-0.9.7/lib/chef/knife/vsphere_vm_execute.rb:63:in `run': undefined method `processManager' for nil:NilClass (NoMethodError)
	from /var/lib/gems/1.9.1/gems/chef-11.8.2/lib/chef/knife.rb:485:in `run_with_pretty_exceptions'
	from /var/lib/gems/1.9.1/gems/chef-11.8.2/lib/chef/knife.rb:174:in `run'
	from /var/lib/gems/1.9.1/gems/chef-11.8.2/lib/chef/application/knife.rb:133:in `run'
	from /var/lib/gems/1.9.1/gems/chef-11.8.2/bin/knife:25:in `<top (required)>'
	from /usr/local/bin/knife:23:in `load'
	from /usr/local/bin/knife:23:in `<main>'

**Comment by swalberg** [comment]
Hi, is this still a problem? Is the guest running the VMWare tools?

Sorry for the very late reply.

**Comment by swalberg** [comment]
Hi, I'm going to close this to try and clean up our backlog of inactive issues. If you are still having this problem, please make sure you're running the latest version of the gem (`gem install knife-vsphere`) first, and then open a new issue so that it goes to the top of the list. Thanks.
