### ISSUE TITLE
vsphere clone vm

### ISSUE THREAD

**Issue by pl33g0r** [ezrapagel/knife-vsphere#87]
I'm trying to create a VM power it on and  bootsrtap. This is the command and errors I am getting. The goal is to create VM and bootstrap after creating it.

****COMMAND****
knife vsphere vm clone new_vm --template centos64-24 --cdomain <domain> -VV --cips <IP> --cdnsip <dns_ip> --cdnssuffix <dns_suffix> --ssh-user <user> -P <passwd> --start --bootstrap true -N new_vm -s <IP_ADDRESS:443> --distro chef-client

****ERROR****

Cloning template centos64-24 to new VM new_vm
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/rbvmomi-1.5.1/lib/rbvmomi/vim/Task.rb:11:in `wait_for_completion': InvalidArgument: A specified parameter was not correct.  (RbVmomi::Fault)
spec.identity.hostName
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/knife-vsphere-0.9.8/lib/chef/knife/vsphere_vm_clone.rb:230:in `run'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.8.2/lib/chef/knife.rb:485:in `run_with_pretty_exceptions'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.8.2/lib/chef/knife.rb:174:in `run'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.8.2/lib/chef/application/knife.rb:133:in `run'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.8.2/bin/knife:25:in `<top (required)>'
	from /usr/bin/knife:23:in `load'
	from /usr/bin/knife:23:in `<main>'

Thanks for the help!

**Comment by swalberg** [comment]
Hi, I think jprosevear is right -- there are no values passed to the options. I'll close this issue for now since it's old, but feel free to re-open it if there are still problems.

**Comment by doker78** [comment]
this issue  is still  persist - can someone point me to the solution of this ?

**Comment by swalberg** [comment]
Hi, this issue is fairly old, can you update us with the command you're running and the full output, please? Run it with `-VV` if possible, and X out any sensitive stuff.
