### ISSUE TITLE
new problem with vsphere_datastorecluster_maxfree.rb

### ISSUE THREAD

**Issue by hinder90** [ezrapagel/knife-vsphere#88]
I am setting up knife-vsphere on a new host and when I attempt to do anything with datastore it fails with VsphereDatastoreclusterMaxfree being undefined:

https://gist.github.com/hinder90/8851323

Could this be related to https://github.com/ezrapagel/knife-vsphere/pull/78 ?

**Comment by swalberg** [comment]
There have been a few improvements in this area, so please try with the latest version. Otherwise, let me know and we'll have a look. Thanks -Sean
