### ISSUE TITLE
knife vsphere template list displays nothing

### ISSUE THREAD

**Issue by bdfarris** [ezrapagel/knife-vsphere#92]
I'm running Chef 11.10.4 and have been bootstrapping and deploying ec2 instances without issue. I now want to bootstrap vmware (Ubuntu and CentOS) templates that I've created (with vmtools installed). The knife vsphere vm list command works, but for some reason I cannot perform knife vsphere template list and therefore cannot launch an instance based upon my templates since chef doesnt see the templates. I'm running ESX 5.0 along with vCenter 5.0. I have the same issue with knife esx template list as well. Any ideas ? I did have to remove rbvmomi (1.8.1) to get rid of the compatibility messages

rbvmomi (1.5.1)
json (1.8.1, 1.5.5)
knife-ec2 (0.6.6)
knife-esx (0.3.5)
knife-vsphere (0.9.8)
knife-windows (0.5.14)

**Comment by swalberg** [comment]
Seems like this is taken care of? I'm going to close this issue now, please re-open or open a new issue if there are continued problems.
